# This route is required!
AzokalHomePage:
    path:     /
    defaults: { _controller: Themes\AzokalTheme\AzokalThemeApp::homeAction }
AzokalHomePageLocale:
    path:     /{_locale}
    defaults: { _controller: Themes\AzokalTheme\AzokalThemeApp::homeAction }
    requirements:
        # Use every 2 letter codes (quick and dirty)
        _locale: "[a-z]{2}"

AzokalSitemap:
    path:     /sitemap.xml
    defaults: { _controller: Themes\AzokalTheme\Controllers\SitemapController::indexAction }
AzokalRemoveTrailingSlash:
    path: /{url}
    defaults: { _controller: Themes\AzokalTheme\AzokalThemeApp::removeTrailingSlashAction }
    requirements:
        url: .*/$
    methods: [GET]
